---

- name: Install packages
  apt:
    state: present
    name:
      - vim
      - tmux
      - krb5-user
  when: ansible_distribution == "debian"

- name: Add Microsoft gpg key
  apt_key:
  url: "https://packages.microsoft.com/keys/microsoft.asc"
  state: present
  when: ansible_distribution == "debian"

- name: Add Spotify gpg key
  apt_key:
  url: "https://download.spotify.com/debian/pubkey.gpg"
  state: present
  when: ansible_distribution == "debian"

- name: Add Teams repo
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main'
    filename: teams
    state: present
    update_cache: yes
  when: ansible_distribution == "debian"

- name: Add Microsoft repo
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/debian/10/prod buster main'
    filename: microsoft-prod
    state: present
    update_cache: yes
  when: ansible_distribution == "debian"

- name: Add vscode repo
  apt_repository:
    repo: 'deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main'
    filename: vscode
    state: present
    update_cache: yes
  when: ansible_distribution == "debian"

- name: Add Spotify repo
  apt_repository:
    repo: 'deb http://repository.spotify.com stable non-free'
    filename: spotify
    state: present
    update_cache: yes
  when: ansible_distribution == "debian"

- name: Install Teams
  apt:
    name: teams
    state: present
  when: ansible_distribution == "debian"

- name: Install powershell 7
  apt:
    name: powershell
    state: present
  when: ansible_distribution == "debian"

- name: Install vscode
  apt:
    name: code
    state: present
  when: ansible_distribution == "debian"

- name: Install dotnetcore 3.1 sdk
  apt:
    name: dotnet-sdk-3.1
    state: present
  when: ansible_distribution == "debian"