---
- name: Install packages
  apt:
    state: present
    name:
      - vim
      - tmux

- name: Add Microst gpg key
  apt_key:
   url: "https://packages.microsoft.com/keys/microsoft.asc"
   state: present

- name: Add Teams repo
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main'
    filename: teams.list
    state: present
    update_cache: yes

- name: Add Microsoft repo
  apt_repository:
    repo: 'deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/debian/10/prod buster main'
    filename: microsoft-prod.list
    state: present
    update_cache: yes

- name: Add vscode repo
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    filename: vscode.list
    state: present
    update_cache: yes

- name: Install Teams
  apt:
    name: teams
    state: present

- name: Install powershell 7
  apt:
    name: powershell
    state: present

- name: Install vscode
  apt:
    name: code
    state: present
